AWSTemplateFormatVersion: "2010-09-09"
Description: "Launches infrastructure for SPA on S3"
Parameters:
  # User-defined values that will be used when creating AWS resources
  S3BucketName:
    Description: Name of the bucket that will host the dashboard. Pass value as parameter when creating template.
    Type: String
  SPADomain:
    Description: Domain the app will be hosted on. Pass value as parameter when creating template.
    Type: String
  IndexPagePath:
    Description: Path to entry point
    Type: String
    Default: index.html
  ErrorPagePath:
    Description: Path to error handler
    Type: String
    Default: 404.html
  DefaultRegion:
    Description: Region for resource creation
    Type: String
    Default: us-east-1
Resources:
  # S3 Bucket && CloudFront Distribution

  # Creates a bucket for hosting
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      WebsiteConfiguration:
        ErrorDocument: !Ref ErrorPagePath
        IndexDocument: !Ref IndexPagePath

  # CloudFront configuration for the bucket
  BucketCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CustomErrorResponses:
        - ErrorCode: 403
          ResponseCode: 404
          ResponsePagePath: !Ref ErrorPagePath
        DefaultRootObject: !Ref IndexPagePath
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !GetAtt AppBucket.DomainName
          Id: s3origin
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontDistributionIdentity}
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontCertificate
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        # Caching Behavior from https://forestry.io/blog/automate-your-static-hosting-environment-with-aws-cloudformation/
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600 # in seconds
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 86400 # in seconds
          MinTTL: 60 # in seconds
          TargetOriginId: s3origin
          ViewerProtocolPolicy: "allow-all"
  CloudFrontDistributionIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AppBucket
  BucketReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppBucket
      PolicyDocument:
        Statement:
          - Action: S3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${AppBucket}/*
            Principal:
              CanonicalUser: !GetAtt CloudFrontDistributionIdentity.S3CanonicalUserId
  # Identity for writing to bucket
  AppPublisher:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: !Sub publish-to-${AppBucket}
          PolicyDocument:
            Statement:
              - Action: s3:*
                Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${AppBucket}
                  - !Sub arn:aws:s3:::${AppBucket}/*
  # Credentials for writing to bucket
  AppPublisherCredentials:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref AppPublisher
  # Domain for hosting the app, creates RecordSet linked to the CloudFront Distribution
  AppRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref SPADomain
      Type: A
      AliasTarget: !Ref BucketCloudFrontDistribution
      HostedZoneId: Z2FDTNDATAQYW2
      Region: !Ref DefaultRegion
      Comment: DNS settings for Cloudfront Distribution
  # CloudFront certificate
  CloudFrontCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref SPADomain
      ValidationMethod: DNS
Outputs:
# Important information that should be provided to the user after the resources have been created
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref AppBucket
  AccessKeyId:
    Description: S3 Access Ket
    Value: !Ref AppPublisherCredentials
  AccessKeySecret:
    Description: S3 Secret Key
    Value: !GetAtt AppPublisherCredentials.SecretAccessKey
  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref BucketCloudFrontDistribution
  Domain:
    Description: CloudFront Domain
    Value: !GetAtt BucketCloudFrontDistribution.DomainName
  RecordSetDomain:
    Description: Assigned domain to Record Set
    Value: !Ref AppRecordSet
  CertificateId:
    Description: Certificate Manager ID
    Value: !Ref CloudFrontCertificate
